---
kind: pipeline
name: ritesh-ch

platform:
  os: linux
  arch: amd64

steps:
  - name: production
    image: rust:1.53.0-slim
    volumes:
      - name: ssh
        path: /root/.ssh
    commands:
      - sh deploy/deploy.sh production
    when:
      branch: master

volumes:
  - name: ssh
    host:
      path: /root/.ssh
...
